### ISSUE TITLE
Tests dont compile

### ISSUE THREAD

**Issue by BlueSpud** [TomPeng19971208/CS4500_A1_Part2#13]
There is a missing semicolon on line 44 and 70.

Also there is a reference to keys_array which does not exist starting on line 156

**Comment by TomPeng19971208** [comment]
this should already be fixed, can you try to pull the latest code?

**Comment by BlueSpud** [comment]
Still doesn't compile. I had the latest code when this issue was filed

**Comment by TomPeng19971208** [comment]
what's the error? I compiled it locally

**Comment by TomPeng19971208** [comment]
I just pushed some code into it, can you try again? This compiled on my PC, if it fails, can you post the error here?

**Comment by BilobedCarton** [comment]
Doesn't work for us either.
`g++ -o testMap -g -Wall -std=c++11 CS4500_A1_Part2/test-map.cpp
CS4500_A1_Part2/test-map.cpp:1:13: warning: extra tokens at end of #pragma once directive [-Wextra-tokens]
#pragma once;
            ^
            //
CS4500_A1_Part2/test-map.cpp:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
#pragma once;
        ^
CS4500_A1_Part2/test-map.cpp:20:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_1 = new String("Hello");
                                ^
CS4500_A1_Part2/test-map.cpp:21:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_1 = new String("1");
                                ^
CS4500_A1_Part2/test-map.cpp:22:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_2 = new String("World");
                                ^
CS4500_A1_Part2/test-map.cpp:23:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_2 = new String("2");
                                ^
CS4500_A1_Part2/test-map.cpp:37:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_1 = new String("Hello");
                                ^
CS4500_A1_Part2/test-map.cpp:38:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_1 = new String("1");
                                ^
CS4500_A1_Part2/test-map.cpp:39:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_2 = new String("2");
                                ^
CS4500_A1_Part2/test-map.cpp:44:45: error: expected ';' after expression
    t_false(val_1 -> equals(h1->get(key_1)))
                                            ^
                                            ;
CS4500_A1_Part2/test-map.cpp:54:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_1 = new String("Hello");
                                ^
CS4500_A1_Part2/test-map.cpp:55:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_1 = new String("1");
                                ^
CS4500_A1_Part2/test-map.cpp:56:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_2 = new String("World");
                                ^
CS4500_A1_Part2/test-map.cpp:57:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_2 = new String("2");
                                ^
CS4500_A1_Part2/test-map.cpp:70:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    t_true(h1 -> get(new String("1")) == nullptr)
                                ^
CS4500_A1_Part2/test-map.cpp:70:50: error: expected ';' after expression
    t_true(h1 -> get(new String("1")) == nullptr)
                                                 ^
                                                 ;
CS4500_A1_Part2/test-map.cpp:83:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_1 = new String("Hello");
                                ^
CS4500_A1_Part2/test-map.cpp:84:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_1 = new String("1");
                                ^
CS4500_A1_Part2/test-map.cpp:85:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_2 = new String("World");
                                ^
CS4500_A1_Part2/test-map.cpp:86:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_2 = new String("2");
                                ^
CS4500_A1_Part2/test-map.cpp:101:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_1 = new String("Hello");
                                ^
CS4500_A1_Part2/test-map.cpp:102:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_1 = new String("1");
                                ^
CS4500_A1_Part2/test-map.cpp:103:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_2 = new String("World");
                                ^
CS4500_A1_Part2/test-map.cpp:104:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_2 = new String("2");
                                ^
CS4500_A1_Part2/test-map.cpp:105:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_3 = new String("NEU");
                                ^
CS4500_A1_Part2/test-map.cpp:121:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_1 = new String("A");
                                ^
CS4500_A1_Part2/test-map.cpp:122:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_1 = new String("1");
                                ^
CS4500_A1_Part2/test-map.cpp:123:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_2 = new String("B");
                                ^
CS4500_A1_Part2/test-map.cpp:124:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_2 = new String("2");
                                ^
CS4500_A1_Part2/test-map.cpp:125:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_3 = new String("C");
                                ^
CS4500_A1_Part2/test-map.cpp:126:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_3 = new String("3");
                                ^
CS4500_A1_Part2/test-map.cpp:145:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_1 = new String("A");
                                ^
CS4500_A1_Part2/test-map.cpp:146:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_1 = new String("1");
                                ^
CS4500_A1_Part2/test-map.cpp:147:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_2 = new String("B");
                                ^
CS4500_A1_Part2/test-map.cpp:148:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_2 = new String("2");
                                ^
CS4500_A1_Part2/test-map.cpp:149:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * key_3 = new String("C");
                                ^
CS4500_A1_Part2/test-map.cpp:150:33: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    String * val_3 = new String("3");
                                ^
CS4500_A1_Part2/test-map.cpp:156:28: error: use of undeclared identifier 'keys_array'
    t_true(val_1 -> equals(keys_array[0]));
                           ^
CS4500_A1_Part2/test-map.cpp:157:28: error: use of undeclared identifier 'keys_array'
    t_true(val_2 -> equals(keys_array[1]));
                           ^
CS4500_A1_Part2/test-map.cpp:158:28: error: use of undeclared identifier 'keys_array'
    t_true(val_3 -> equals(keys_array[2]));
                           ^
35 warnings and 5 errors generated.`

**Comment by TomPeng19971208** [comment]
yours is not the latest, pull again plz

**Comment by eccabay** [comment]
Your most recent commit (which we use in the given Makefile that checks out your repo) does not compile. This is because you include <iostream> after including string.h and map.h. If you move it above those two instead of having it below, it will compile.
